// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmsf1W1sDEcpa8XKl7E9yTGB6TQs93268',
    appId: '1:385320094479:web:5de8dcf4548357fe294c7a',
    messagingSenderId: '385320094479',
    projectId: 'newfirebase-21403',
    authDomain: 'newfirebase-21403.firebaseapp.com',
    storageBucket: 'newfirebase-21403.appspot.com',
    measurementId: 'G-0W70JP513H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5NlamHgXF5oKFygOCUP6FwnFfRk7yHxY',
    appId: '1:385320094479:android:0cd2d3fe5502a199294c7a',
    messagingSenderId: '385320094479',
    projectId: 'newfirebase-21403',
    storageBucket: 'newfirebase-21403.appspot.com',
  );
}
